### ISSUE TITLE
可以实现基于mvc的baseActivity吗

### ISSUE THREAD

**Issue by candebbs** [lihangleo2/SelfMVP#2]
因为有一些界面是比较简单，不必mvp了。

**Comment by lihangleo2** [comment]
如果不需要mvp的话，还是继承那个BaseActivity只不过，要返回Presenter的示范返回null
`    @Override
    public BasePresenter cretaePresenter() {
        return null;
    }`

**Comment by lihangleo2** [comment]
因为我没有封装model层，直接把网络请求封装在了BasePresenter里。如果需要用联网的话，就要一步一步写了，如
`RetrofitManager.getApiService().getGank("参数").subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(gankFatherBean ->{

                });`

**Comment by lihangleo2** [comment]
当然你也可以看我之前一篇mvc的文章，直接封装一个https://github.com/lihangleo2/SelfMVC。不过我建议学习jitpack用MVVM。这是我觉得前段框架中，最好用的一个
